packages:
  - packages/*
  - packages/contracts/*
  - packages/legacy/*

gitChecks: false

onlyBuiltDependencies:
  - '@parcel/watcher'
  - canvas
  - esbuild
  - fs-ext-extra-prebuilt
  - koffi
  - msgpackr-extract
  - protobufjs

overrides:
  '@open-hax/eta-mu-monorepo': 'link:'
