packages:
  - packages/*
  - packages/legacy/*
  - services/*
  - shared/*

gitChecks: false

onlyBuiltDependencies:
  - '@parcel/watcher'
  - canvas
  - esbuild
  - koffi
  - msgpackr-extract
  - protobufjs

overrides:
  '@open-hax/eta-mu-monorepo': 'link:'
