import "./cljs_env.js";
import "./cljs.core.js";
import "./honey.sql.helpers.js";
goog.provide('knoxx.backend.shape.db.roles');
knoxx.backend.shape.db.roles.by_id = (function knoxx$backend$shape$db$roles$by_id(role_id){
return honey.sql.helpers.where.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.from.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.select.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([new cljs.core.Keyword(null,"*","*",-1294732318)], 0)),new cljs.core.Keyword(null,"roles","roles",143379530)], 0)),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"=","=",1152933628),new cljs.core.Keyword(null,"id","id",-1388402092),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"cast","cast",-1761029143),role_id,new cljs.core.Keyword(null,"uuid","uuid",-2145095719)], null)], null)], 0));
});
/**
 * Platform-scoped (org_id IS NULL) or org-scoped role by slug.
 */
knoxx.backend.shape.db.roles.by_slug = (function knoxx$backend$shape$db$roles$by_slug(p__31188){
var map__31189 = p__31188;
var map__31189__$1 = cljs.core.__destructure_map(map__31189);
var slug = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__31189__$1,new cljs.core.Keyword(null,"slug","slug",2029314850));
var org_id = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__31189__$1,new cljs.core.Keyword(null,"org-id","org-id",1485182668));
return honey.sql.helpers.limit.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.where.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.from.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.select.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([new cljs.core.Keyword(null,"*","*",-1294732318)], 0)),new cljs.core.Keyword(null,"roles","roles",143379530)], 0)),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"and","and",-971899817),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"=","=",1152933628),new cljs.core.Keyword(null,"slug","slug",2029314850),slug], null),(((org_id == null))?new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"=","=",1152933628),new cljs.core.Keyword(null,"org_id","org_id",1380185385),null], null):new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"=","=",1152933628),new cljs.core.Keyword(null,"org_id","org_id",1380185385),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"cast","cast",-1761029143),org_id,new cljs.core.Keyword(null,"uuid","uuid",-2145095719)], null)], null))], null)], 0)),(1)], 0));
});
knoxx.backend.shape.db.roles.by_ids = (function knoxx$backend$shape$db$roles$by_ids(role_ids){
return honey.sql.helpers.order_by.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.where.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.from.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.select.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([new cljs.core.Keyword(null,"*","*",-1294732318)], 0)),new cljs.core.Keyword(null,"roles","roles",143379530)], 0)),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"in","in",-1531184865),new cljs.core.Keyword(null,"id","id",-1388402092),cljs.core.mapv.cljs$core$IFn$_invoke$arity$2((function (id){
return new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"cast","cast",-1761029143),id,new cljs.core.Keyword(null,"uuid","uuid",-2145095719)], null);
}),role_ids)], null)], 0)),new cljs.core.Keyword(null,"name","name",1843675177)], 0));
});
/**
 * Return id + slug for a seq of slugs, checking both platform and org scope.
 */
knoxx.backend.shape.db.roles.by_slugs_and_org = (function knoxx$backend$shape$db$roles$by_slugs_and_org(slugs,org_id){
return honey.sql.helpers.where.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.from.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.select.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([new cljs.core.Keyword(null,"id","id",-1388402092),new cljs.core.Keyword(null,"slug","slug",2029314850)], 0)),new cljs.core.Keyword(null,"roles","roles",143379530)], 0)),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"and","and",-971899817),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"in","in",-1531184865),new cljs.core.Keyword(null,"slug","slug",2029314850),slugs], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"or","or",235744169),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"=","=",1152933628),new cljs.core.Keyword(null,"org_id","org_id",1380185385),null], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"=","=",1152933628),new cljs.core.Keyword(null,"org_id","org_id",1380185385),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"cast","cast",-1761029143),org_id,new cljs.core.Keyword(null,"uuid","uuid",-2145095719)], null)], null)], null)], null)], 0));
});
knoxx.backend.shape.db.roles.list_all = (function knoxx$backend$shape$db$roles$list_all(){
return honey.sql.helpers.order_by.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.from.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.select.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([new cljs.core.Keyword(null,"*","*",-1294732318)], 0)),new cljs.core.Keyword(null,"roles","roles",143379530)], 0)),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"built_in","built_in",-655972882),new cljs.core.Keyword(null,"desc","desc",2093485764)], null),new cljs.core.Keyword(null,"name","name",1843675177)], 0));
});
knoxx.backend.shape.db.roles.list_by_org = (function knoxx$backend$shape$db$roles$list_by_org(org_id){
return honey.sql.helpers.order_by.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.where.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.from.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.select.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([new cljs.core.Keyword(null,"*","*",-1294732318)], 0)),new cljs.core.Keyword(null,"roles","roles",143379530)], 0)),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"=","=",1152933628),new cljs.core.Keyword(null,"org_id","org_id",1380185385),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"cast","cast",-1761029143),org_id,new cljs.core.Keyword(null,"uuid","uuid",-2145095719)], null)], null)], 0)),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"built_in","built_in",-655972882),new cljs.core.Keyword(null,"desc","desc",2093485764)], null),new cljs.core.Keyword(null,"name","name",1843675177)], 0));
});
knoxx.backend.shape.db.roles.insert = (function knoxx$backend$shape$db$roles$insert(p__31216){
var map__31219 = p__31216;
var map__31219__$1 = cljs.core.__destructure_map(map__31219);
var org_id = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__31219__$1,new cljs.core.Keyword(null,"org-id","org-id",1485182668));
var name = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__31219__$1,new cljs.core.Keyword(null,"name","name",1843675177));
var slug = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__31219__$1,new cljs.core.Keyword(null,"slug","slug",2029314850));
var scope_kind = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__31219__$1,new cljs.core.Keyword(null,"scope-kind","scope-kind",-2016316465));
var built_in = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__31219__$1,new cljs.core.Keyword(null,"built-in","built-in",1245067766));
var system_managed = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__31219__$1,new cljs.core.Keyword(null,"system-managed","system-managed",-191362489));
return honey.sql.helpers.returning.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.values.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.insert_into.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([new cljs.core.Keyword(null,"roles","roles",143379530)], 0)),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentArrayMap(null, 6, [new cljs.core.Keyword(null,"org_id","org_id",1380185385),(cljs.core.truth_(org_id)?new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"cast","cast",-1761029143),org_id,new cljs.core.Keyword(null,"uuid","uuid",-2145095719)], null):null),new cljs.core.Keyword(null,"name","name",1843675177),name,new cljs.core.Keyword(null,"slug","slug",2029314850),slug,new cljs.core.Keyword(null,"scope_kind","scope_kind",-491935188),scope_kind,new cljs.core.Keyword(null,"built_in","built_in",-655972882),built_in,new cljs.core.Keyword(null,"system_managed","system_managed",-1147228921),system_managed], null)], null)], 0)),new cljs.core.Keyword(null,"*","*",-1294732318)], 0));
});
knoxx.backend.shape.db.roles.update_role = (function knoxx$backend$shape$db$roles$update_role(role_id,p__31266){
var map__31271 = p__31266;
var map__31271__$1 = cljs.core.__destructure_map(map__31271);
var name = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__31271__$1,new cljs.core.Keyword(null,"name","name",1843675177));
var scope_kind = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__31271__$1,new cljs.core.Keyword(null,"scope-kind","scope-kind",-2016316465));
var built_in = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__31271__$1,new cljs.core.Keyword(null,"built-in","built-in",1245067766));
var system_managed = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__31271__$1,new cljs.core.Keyword(null,"system-managed","system-managed",-191362489));
return honey.sql.helpers.returning.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.where.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.set.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.update.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([new cljs.core.Keyword(null,"roles","roles",143379530)], 0)),new cljs.core.PersistentArrayMap(null, 5, [new cljs.core.Keyword(null,"name","name",1843675177),name,new cljs.core.Keyword(null,"scope_kind","scope_kind",-491935188),scope_kind,new cljs.core.Keyword(null,"built_in","built_in",-655972882),built_in,new cljs.core.Keyword(null,"system_managed","system_managed",-1147228921),system_managed,new cljs.core.Keyword(null,"updated_at","updated_at",-460224592),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"now","now",-1650525531)], null)], null)], 0)),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"=","=",1152933628),new cljs.core.Keyword(null,"id","id",-1388402092),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"cast","cast",-1761029143),role_id,new cljs.core.Keyword(null,"uuid","uuid",-2145095719)], null)], null)], 0)),new cljs.core.Keyword(null,"*","*",-1294732318)], 0));
});
/**
 * permission_code rows for a set of role ids (modern schema).
 */
knoxx.backend.shape.db.roles.permissions_for_roles = (function knoxx$backend$shape$db$roles$permissions_for_roles(role_ids){
return honey.sql.helpers.order_by.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.where.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.from.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.select.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([new cljs.core.Keyword(null,"role_id","role_id",1603615897),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"permission_code","permission_code",-2022293866),new cljs.core.Keyword(null,"code","code",1586293142)], null)], 0)),new cljs.core.Keyword(null,"role_permissions","role_permissions",1036030749)], 0)),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"in","in",-1531184865),new cljs.core.Keyword(null,"role_id","role_id",1603615897),cljs.core.mapv.cljs$core$IFn$_invoke$arity$2((function (id){
return new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"cast","cast",-1761029143),id,new cljs.core.Keyword(null,"uuid","uuid",-2145095719)], null);
}),role_ids)], null)], 0)),new cljs.core.Keyword(null,"permission_code","permission_code",-2022293866)], 0));
});
/**
 * permission_code via join on permissions table (legacy schema).
 */
knoxx.backend.shape.db.roles.permissions_for_roles_legacy = (function knoxx$backend$shape$db$roles$permissions_for_roles_legacy(role_ids){
return honey.sql.helpers.order_by.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.where.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.join.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.from.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.select.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([new cljs.core.Keyword(null,"rp.role_id","rp.role_id",-2009577127),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"p.code","p.code",-2076537273),new cljs.core.Keyword(null,"code","code",1586293142)], null)], 0)),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"role_permissions","role_permissions",1036030749),new cljs.core.Keyword(null,"rp","rp",2006698083)], null)], 0)),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"permissions","permissions",67803075),new cljs.core.Keyword(null,"p","p",151049309)], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"=","=",1152933628),new cljs.core.Keyword(null,"p.id","p.id",1788457993),new cljs.core.Keyword(null,"rp.permission_id","rp.permission_id",-113035486)], null)], 0)),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"in","in",-1531184865),new cljs.core.Keyword(null,"rp.role_id","rp.role_id",-2009577127),cljs.core.mapv.cljs$core$IFn$_invoke$arity$2((function (id){
return new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"cast","cast",-1761029143),id,new cljs.core.Keyword(null,"uuid","uuid",-2145095719)], null);
}),role_ids)], null)], 0)),new cljs.core.Keyword(null,"p.code","p.code",-2076537273)], 0));
});
knoxx.backend.shape.db.roles.delete_permissions = (function knoxx$backend$shape$db$roles$delete_permissions(role_id){
return honey.sql.helpers.where.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.delete_from.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([new cljs.core.Keyword(null,"role_permissions","role_permissions",1036030749)], 0)),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"=","=",1152933628),new cljs.core.Keyword(null,"role_id","role_id",1603615897),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"cast","cast",-1761029143),role_id,new cljs.core.Keyword(null,"uuid","uuid",-2145095719)], null)], null)], 0));
});
knoxx.backend.shape.db.roles.insert_permission_modern = (function knoxx$backend$shape$db$roles$insert_permission_modern(role_id,code){
return honey.sql.helpers.do_update_set.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.on_conflict.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.values.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.insert_into.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([new cljs.core.Keyword(null,"role_permissions","role_permissions",1036030749)], 0)),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentArrayMap(null, 3, [new cljs.core.Keyword(null,"role_id","role_id",1603615897),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"cast","cast",-1761029143),role_id,new cljs.core.Keyword(null,"uuid","uuid",-2145095719)], null),new cljs.core.Keyword(null,"permission_code","permission_code",-2022293866),code,new cljs.core.Keyword(null,"effect","effect",347343289),"allow"], null)], null)], 0)),new cljs.core.Keyword(null,"role_id","role_id",1603615897),new cljs.core.Keyword(null,"permission_code","permission_code",-2022293866)], 0)),new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"effect","effect",347343289),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"raw","raw",1604651272),"EXCLUDED.effect"], null)], null)], 0));
});
knoxx.backend.shape.db.roles.tool_policies_for_roles = (function knoxx$backend$shape$db$roles$tool_policies_for_roles(role_ids){
return honey.sql.helpers.order_by.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.where.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.from.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.select.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([new cljs.core.Keyword(null,"rtp.role_id","rtp.role_id",1402415796),new cljs.core.Keyword(null,"rtp.tool_id","rtp.tool_id",193039540),new cljs.core.Keyword(null,"rtp.effect","rtp.effect",-24157277),new cljs.core.Keyword(null,"rtp.constraints_json","rtp.constraints_json",-1986016140)], 0)),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"role_tool_policies","role_tool_policies",-706114099),new cljs.core.Keyword(null,"rtp","rtp",-2009461645)], null)], 0)),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"in","in",-1531184865),new cljs.core.Keyword(null,"rtp.role_id","rtp.role_id",1402415796),cljs.core.mapv.cljs$core$IFn$_invoke$arity$2((function (id){
return new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"cast","cast",-1761029143),id,new cljs.core.Keyword(null,"uuid","uuid",-2145095719)], null);
}),role_ids)], null)], 0)),new cljs.core.Keyword(null,"rtp.tool_id","rtp.tool_id",193039540)], 0));
});
knoxx.backend.shape.db.roles.delete_tool_policies = (function knoxx$backend$shape$db$roles$delete_tool_policies(role_id){
return honey.sql.helpers.where.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.delete_from.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([new cljs.core.Keyword(null,"role_tool_policies","role_tool_policies",-706114099)], 0)),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"=","=",1152933628),new cljs.core.Keyword(null,"role_id","role_id",1603615897),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"cast","cast",-1761029143),role_id,new cljs.core.Keyword(null,"uuid","uuid",-2145095719)], null)], null)], 0));
});
knoxx.backend.shape.db.roles.insert_tool_policy = (function knoxx$backend$shape$db$roles$insert_tool_policy(role_id,p__31335){
var map__31337 = p__31335;
var map__31337__$1 = cljs.core.__destructure_map(map__31337);
var tool_id = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__31337__$1,new cljs.core.Keyword(null,"tool-id","tool-id",-290456894));
var effect = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__31337__$1,new cljs.core.Keyword(null,"effect","effect",347343289));
var constraints_json = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__31337__$1,new cljs.core.Keyword(null,"constraints-json","constraints-json",-1677970568));
return honey.sql.helpers.do_update_set.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.on_conflict.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.values.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.insert_into.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([new cljs.core.Keyword(null,"role_tool_policies","role_tool_policies",-706114099)], 0)),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentArrayMap(null, 4, [new cljs.core.Keyword(null,"role_id","role_id",1603615897),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"cast","cast",-1761029143),role_id,new cljs.core.Keyword(null,"uuid","uuid",-2145095719)], null),new cljs.core.Keyword(null,"tool_id","tool_id",1550520216),tool_id,new cljs.core.Keyword(null,"effect","effect",347343289),effect,new cljs.core.Keyword(null,"constraints_json","constraints_json",1549946864),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"cast","cast",-1761029143),constraints_json,new cljs.core.Keyword(null,"jsonb","jsonb",-826402072)], null)], null)], null)], 0)),new cljs.core.Keyword(null,"role_id","role_id",1603615897),new cljs.core.Keyword(null,"tool_id","tool_id",1550520216)], 0)),new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"effect","effect",347343289),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"raw","raw",1604651272),"EXCLUDED.effect"], null),new cljs.core.Keyword(null,"constraints_json","constraints_json",1549946864),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"raw","raw",1604651272),"EXCLUDED.constraints_json"], null)], null)], 0));
});
/**
 * Role rows joined via membership_roles for a set of membership ids.
 */
knoxx.backend.shape.db.roles.roles_for_memberships = (function knoxx$backend$shape$db$roles$roles_for_memberships(membership_ids){
return honey.sql.helpers.order_by.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.where.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.join.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.from.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.select.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([new cljs.core.Keyword(null,"mr.membership_id","mr.membership_id",2087918915),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"r.id","r.id",639509055),new cljs.core.Keyword(null,"role_id","role_id",1603615897)], null),new cljs.core.Keyword(null,"r.slug","r.slug",1852515631),new cljs.core.Keyword(null,"r.name","r.name",-690288804),new cljs.core.Keyword(null,"r.scope_kind","r.scope_kind",-513331138),new cljs.core.Keyword(null,"r.org_id","r.org_id",385902088)], 0)),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"membership_roles","membership_roles",-742165374),new cljs.core.Keyword(null,"mr","mr",-1224518357)], null)], 0)),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"roles","roles",143379530),new cljs.core.Keyword(null,"r","r",-471384190)], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"=","=",1152933628),new cljs.core.Keyword(null,"r.id","r.id",639509055),new cljs.core.Keyword(null,"mr.role_id","mr.role_id",304528246)], null)], 0)),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"in","in",-1531184865),new cljs.core.Keyword(null,"mr.membership_id","mr.membership_id",2087918915),cljs.core.mapv.cljs$core$IFn$_invoke$arity$2((function (id){
return new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"cast","cast",-1761029143),id,new cljs.core.Keyword(null,"uuid","uuid",-2145095719)], null);
}),membership_ids)], null)], 0)),new cljs.core.Keyword(null,"r.name","r.name",-690288804)], 0));
});
knoxx.backend.shape.db.roles.insert_membership_role = (function knoxx$backend$shape$db$roles$insert_membership_role(membership_id,role_id){
return honey.sql.helpers.do_nothing.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.on_conflict.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.values.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.insert_into.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([new cljs.core.Keyword(null,"membership_roles","membership_roles",-742165374)], 0)),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"membership_id","membership_id",-171302674),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"cast","cast",-1761029143),membership_id,new cljs.core.Keyword(null,"uuid","uuid",-2145095719)], null),new cljs.core.Keyword(null,"role_id","role_id",1603615897),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"cast","cast",-1761029143),role_id,new cljs.core.Keyword(null,"uuid","uuid",-2145095719)], null)], null)], null)], 0)),new cljs.core.Keyword(null,"membership_id","membership_id",-171302674),new cljs.core.Keyword(null,"role_id","role_id",1603615897)], 0))], 0));
});

//# sourceMappingURL=knoxx.backend.shape.db.roles.js.map
