import "./cljs_env.js";
import "./cljs.core.js";
import "./honey.sql.helpers.js";
goog.provide('knoxx.backend.shape.db.invites');
knoxx.backend.shape.db.invites.insert = (function knoxx$backend$shape$db$invites$insert(p__31183){
var map__31185 = p__31183;
var map__31185__$1 = cljs.core.__destructure_map(map__31185);
var org_id = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__31185__$1,new cljs.core.Keyword(null,"org-id","org-id",1485182668));
var code = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__31185__$1,new cljs.core.Keyword(null,"code","code",1586293142));
var email = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__31185__$1,new cljs.core.Keyword(null,"email","email",1415816706));
var inviter_membership_id = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__31185__$1,new cljs.core.Keyword(null,"inviter-membership-id","inviter-membership-id",294607735));
var role_slugs_json = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__31185__$1,new cljs.core.Keyword(null,"role-slugs-json","role-slugs-json",-1985294108));
var expires_at = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__31185__$1,new cljs.core.Keyword(null,"expires-at","expires-at",1654982210));
return honey.sql.helpers.returning.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.values.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.insert_into.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([new cljs.core.Keyword(null,"invites","invites",1962160761)], 0)),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentArrayMap(null, 7, [new cljs.core.Keyword(null,"org_id","org_id",1380185385),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"cast","cast",-1761029143),org_id,new cljs.core.Keyword(null,"uuid","uuid",-2145095719)], null),new cljs.core.Keyword(null,"code","code",1586293142),code,new cljs.core.Keyword(null,"email","email",1415816706),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"lower","lower",1120320821),email], null),new cljs.core.Keyword(null,"inviter_membership_id","inviter_membership_id",1772406330),(cljs.core.truth_(inviter_membership_id)?new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"cast","cast",-1761029143),inviter_membership_id,new cljs.core.Keyword(null,"uuid","uuid",-2145095719)], null):null),new cljs.core.Keyword(null,"role_slugs","role_slugs",2101192325),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"raw","raw",1604651272),role_slugs_json], null),new cljs.core.Keyword(null,"status","status",-1997798413),"pending",new cljs.core.Keyword(null,"expires_at","expires_at",-423028958),expires_at], null)], null)], 0)),new cljs.core.Keyword(null,"*","*",-1294732318)], 0));
});
knoxx.backend.shape.db.invites.pending_by_code = (function knoxx$backend$shape$db$invites$pending_by_code(code){
return honey.sql.helpers.limit.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.where.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.from.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.select.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([new cljs.core.Keyword(null,"*","*",-1294732318)], 0)),new cljs.core.Keyword(null,"invites","invites",1962160761)], 0)),new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"and","and",-971899817),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"=","=",1152933628),new cljs.core.Keyword(null,"code","code",1586293142),code], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"=","=",1152933628),new cljs.core.Keyword(null,"status","status",-1997798413),"pending"], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,">",">",-555517146),new cljs.core.Keyword(null,"expires_at","expires_at",-423028958),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"now","now",-1650525531)], null)], null)], null)], 0)),(1)], 0));
});
knoxx.backend.shape.db.invites.redeem = (function knoxx$backend$shape$db$invites$redeem(invite_id){
return honey.sql.helpers.returning.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.where.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.set.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.update.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([new cljs.core.Keyword(null,"invites","invites",1962160761)], 0)),new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"status","status",-1997798413),"redeemed",new cljs.core.Keyword(null,"redeemed_at","redeemed_at",-1486030703),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"now","now",-1650525531)], null)], null)], 0)),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"=","=",1152933628),new cljs.core.Keyword(null,"id","id",-1388402092),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"cast","cast",-1761029143),invite_id,new cljs.core.Keyword(null,"uuid","uuid",-2145095719)], null)], null)], 0)),new cljs.core.Keyword(null,"*","*",-1294732318)], 0));
});
knoxx.backend.shape.db.invites.list_by_org = (function knoxx$backend$shape$db$invites$list_by_org(org_id){
return honey.sql.helpers.order_by.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.where.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.from.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.select.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([new cljs.core.Keyword(null,"*","*",-1294732318)], 0)),new cljs.core.Keyword(null,"invites","invites",1962160761)], 0)),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"=","=",1152933628),new cljs.core.Keyword(null,"org_id","org_id",1380185385),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"cast","cast",-1761029143),org_id,new cljs.core.Keyword(null,"uuid","uuid",-2145095719)], null)], null)], 0)),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"created_at","created_at",1484050750),new cljs.core.Keyword(null,"desc","desc",2093485764)], null)], 0));
});
knoxx.backend.shape.db.invites.list_by_org_and_status = (function knoxx$backend$shape$db$invites$list_by_org_and_status(org_id,status){
return honey.sql.helpers.order_by.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.where.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.from.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.select.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([new cljs.core.Keyword(null,"*","*",-1294732318)], 0)),new cljs.core.Keyword(null,"invites","invites",1962160761)], 0)),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"and","and",-971899817),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"=","=",1152933628),new cljs.core.Keyword(null,"org_id","org_id",1380185385),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"cast","cast",-1761029143),org_id,new cljs.core.Keyword(null,"uuid","uuid",-2145095719)], null)], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"=","=",1152933628),new cljs.core.Keyword(null,"status","status",-1997798413),status], null)], null)], 0)),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"created_at","created_at",1484050750),new cljs.core.Keyword(null,"desc","desc",2093485764)], null)], 0));
});

//# sourceMappingURL=knoxx.backend.shape.db.invites.js.map
