import "./cljs_env.js";
import "./cljs.core.js";
import "./honey.sql.helpers.js";
goog.provide('knoxx.backend.shape.db.users');
knoxx.backend.shape.db.users.by_id = (function knoxx$backend$shape$db$users$by_id(user_id){
return honey.sql.helpers.where.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.from.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.select.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([new cljs.core.Keyword(null,"*","*",-1294732318)], 0)),new cljs.core.Keyword(null,"users","users",-713552705)], 0)),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"=","=",1152933628),new cljs.core.Keyword(null,"id","id",-1388402092),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"cast","cast",-1761029143),user_id,new cljs.core.Keyword(null,"uuid","uuid",-2145095719)], null)], null)], 0));
});
knoxx.backend.shape.db.users.by_email = (function knoxx$backend$shape$db$users$by_email(email){
return honey.sql.helpers.limit.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.where.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.from.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.select.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([new cljs.core.Keyword(null,"*","*",-1294732318)], 0)),new cljs.core.Keyword(null,"users","users",-713552705)], 0)),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"=","=",1152933628),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"lower","lower",1120320821),new cljs.core.Keyword(null,"email","email",1415816706)], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"lower","lower",1120320821),email], null)], null)], 0)),(1)], 0));
});
knoxx.backend.shape.db.users.list_all = (function knoxx$backend$shape$db$users$list_all(){
return honey.sql.helpers.order_by.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.from.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.select.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([new cljs.core.Keyword(null,"*","*",-1294732318)], 0)),new cljs.core.Keyword(null,"users","users",-713552705)], 0)),new cljs.core.Keyword(null,"display_name","display_name",-1494335013),new cljs.core.Keyword(null,"email","email",1415816706)], 0));
});
knoxx.backend.shape.db.users.list_by_org = (function knoxx$backend$shape$db$users$list_by_org(org_id){
return honey.sql.helpers.order_by.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.where.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.join.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.from.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.select_distinct.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([new cljs.core.Keyword(null,"u.*","u.*",1818232615)], 0)),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"users","users",-713552705),new cljs.core.Keyword(null,"u","u",-1156634785)], null)], 0)),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"memberships","memberships",1865599157),new cljs.core.Keyword(null,"m","m",1632677161)], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"=","=",1152933628),new cljs.core.Keyword(null,"m.user_id","m.user_id",-1368963548),new cljs.core.Keyword(null,"u.id","u.id",1408850436)], null)], 0)),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"=","=",1152933628),new cljs.core.Keyword(null,"m.org_id","m.org_id",-1666616842),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"cast","cast",-1761029143),org_id,new cljs.core.Keyword(null,"uuid","uuid",-2145095719)], null)], null)], 0)),new cljs.core.Keyword(null,"u.display_name","u.display_name",1832179795),new cljs.core.Keyword(null,"u.email","u.email",1640590567)], 0));
});
/**
 * Membership + org info for a set of user-ids, within one org.
 */
knoxx.backend.shape.db.users.memberships_for_users = (function knoxx$backend$shape$db$users$memberships_for_users(user_ids,org_id){
return honey.sql.helpers.order_by.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.where.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.join.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.from.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.select.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([new cljs.core.Keyword(null,"m.*","m.*",-1225802390),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"o.name","o.name",83564940),new cljs.core.Keyword(null,"org_name","org_name",-1732897410)], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"o.slug","o.slug",-675756042),new cljs.core.Keyword(null,"org_slug","org_slug",-322631770)], null)], 0)),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"memberships","memberships",1865599157),new cljs.core.Keyword(null,"m","m",1632677161)], null)], 0)),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"orgs","orgs",155776628),new cljs.core.Keyword(null,"o","o",-1350007228)], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"=","=",1152933628),new cljs.core.Keyword(null,"o.id","o.id",-1100310568),new cljs.core.Keyword(null,"m.org_id","m.org_id",-1666616842)], null)], 0)),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"and","and",-971899817),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"in","in",-1531184865),new cljs.core.Keyword(null,"m.user_id","m.user_id",-1368963548),cljs.core.mapv.cljs$core$IFn$_invoke$arity$2((function (id){
return new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"cast","cast",-1761029143),id,new cljs.core.Keyword(null,"uuid","uuid",-2145095719)], null);
}),user_ids)], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"=","=",1152933628),new cljs.core.Keyword(null,"m.org_id","m.org_id",-1666616842),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"cast","cast",-1761029143),org_id,new cljs.core.Keyword(null,"uuid","uuid",-2145095719)], null)], null)], null)], 0)),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"m.created_at","m.created_at",1807502461),new cljs.core.Keyword(null,"asc","asc",356854569)], null)], 0));
});
/**
 * All memberships for a set of user-ids across all orgs.
 */
knoxx.backend.shape.db.users.all_memberships_for_users = (function knoxx$backend$shape$db$users$all_memberships_for_users(user_ids){
return honey.sql.helpers.order_by.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.where.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.join.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.from.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.select.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([new cljs.core.Keyword(null,"m.*","m.*",-1225802390),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"o.name","o.name",83564940),new cljs.core.Keyword(null,"org_name","org_name",-1732897410)], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"o.slug","o.slug",-675756042),new cljs.core.Keyword(null,"org_slug","org_slug",-322631770)], null)], 0)),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"memberships","memberships",1865599157),new cljs.core.Keyword(null,"m","m",1632677161)], null)], 0)),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"orgs","orgs",155776628),new cljs.core.Keyword(null,"o","o",-1350007228)], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"=","=",1152933628),new cljs.core.Keyword(null,"o.id","o.id",-1100310568),new cljs.core.Keyword(null,"m.org_id","m.org_id",-1666616842)], null)], 0)),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"in","in",-1531184865),new cljs.core.Keyword(null,"m.user_id","m.user_id",-1368963548),cljs.core.mapv.cljs$core$IFn$_invoke$arity$2((function (id){
return new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"cast","cast",-1761029143),id,new cljs.core.Keyword(null,"uuid","uuid",-2145095719)], null);
}),user_ids)], null)], 0)),new cljs.core.Keyword(null,"o.name","o.name",83564940),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"m.created_at","m.created_at",1807502461),new cljs.core.Keyword(null,"asc","asc",356854569)], null)], 0));
});
knoxx.backend.shape.db.users.upsert = (function knoxx$backend$shape$db$users$upsert(p__31328){
var map__31329 = p__31328;
var map__31329__$1 = cljs.core.__destructure_map(map__31329);
var email = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__31329__$1,new cljs.core.Keyword(null,"email","email",1415816706));
var display_name = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__31329__$1,new cljs.core.Keyword(null,"display-name","display-name",694513143));
var auth_provider = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__31329__$1,new cljs.core.Keyword(null,"auth-provider","auth-provider",4882231));
var external_subject = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__31329__$1,new cljs.core.Keyword(null,"external-subject","external-subject",-265707402));
var status = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__31329__$1,new cljs.core.Keyword(null,"status","status",-1997798413));
return honey.sql.helpers.returning.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.do_update_set.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.on_conflict.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.values.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.insert_into.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([new cljs.core.Keyword(null,"users","users",-713552705)], 0)),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentArrayMap(null, 5, [new cljs.core.Keyword(null,"email","email",1415816706),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"lower","lower",1120320821),email], null),new cljs.core.Keyword(null,"display_name","display_name",-1494335013),display_name,new cljs.core.Keyword(null,"auth_provider","auth_provider",-1634726609),auth_provider,new cljs.core.Keyword(null,"external_subject","external_subject",-2123976135),external_subject,new cljs.core.Keyword(null,"status","status",-1997798413),status], null)], null)], 0)),new cljs.core.Keyword(null,"email","email",1415816706)], 0)),new cljs.core.PersistentArrayMap(null, 5, [new cljs.core.Keyword(null,"display_name","display_name",-1494335013),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"raw","raw",1604651272),"EXCLUDED.display_name"], null),new cljs.core.Keyword(null,"auth_provider","auth_provider",-1634726609),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"raw","raw",1604651272),"EXCLUDED.auth_provider"], null),new cljs.core.Keyword(null,"external_subject","external_subject",-2123976135),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"raw","raw",1604651272),"EXCLUDED.external_subject"], null),new cljs.core.Keyword(null,"status","status",-1997798413),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"raw","raw",1604651272),"EXCLUDED.status"], null),new cljs.core.Keyword(null,"updated_at","updated_at",-460224592),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"now","now",-1650525531)], null)], null)], 0)),new cljs.core.Keyword(null,"*","*",-1294732318)], 0));
});
knoxx.backend.shape.db.users.update_user = (function knoxx$backend$shape$db$users$update_user(user_id,p__31376){
var map__31377 = p__31376;
var map__31377__$1 = cljs.core.__destructure_map(map__31377);
var email = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__31377__$1,new cljs.core.Keyword(null,"email","email",1415816706));
var display_name = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__31377__$1,new cljs.core.Keyword(null,"display-name","display-name",694513143));
var status = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__31377__$1,new cljs.core.Keyword(null,"status","status",-1997798413));
var auth_provider = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__31377__$1,new cljs.core.Keyword(null,"auth-provider","auth-provider",4882231));
var external_subject = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__31377__$1,new cljs.core.Keyword(null,"external-subject","external-subject",-265707402));
return honey.sql.helpers.returning.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.where.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.set.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.update.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([new cljs.core.Keyword(null,"users","users",-713552705)], 0)),(function (){var G__31392 = new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"updated_at","updated_at",-460224592),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"now","now",-1650525531)], null)], null);
var G__31392__$1 = (cljs.core.truth_(email)?cljs.core.assoc.cljs$core$IFn$_invoke$arity$3(G__31392,new cljs.core.Keyword(null,"email","email",1415816706),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"lower","lower",1120320821),email], null)):G__31392);
var G__31392__$2 = (cljs.core.truth_(display_name)?cljs.core.assoc.cljs$core$IFn$_invoke$arity$3(G__31392__$1,new cljs.core.Keyword(null,"display_name","display_name",-1494335013),display_name):G__31392__$1);
var G__31392__$3 = (cljs.core.truth_(status)?cljs.core.assoc.cljs$core$IFn$_invoke$arity$3(G__31392__$2,new cljs.core.Keyword(null,"status","status",-1997798413),status):G__31392__$2);
var G__31392__$4 = (cljs.core.truth_(auth_provider)?cljs.core.assoc.cljs$core$IFn$_invoke$arity$3(G__31392__$3,new cljs.core.Keyword(null,"auth_provider","auth_provider",-1634726609),auth_provider):G__31392__$3);
if(cljs.core.truth_(external_subject)){
return cljs.core.assoc.cljs$core$IFn$_invoke$arity$3(G__31392__$4,new cljs.core.Keyword(null,"external_subject","external_subject",-2123976135),external_subject);
} else {
return G__31392__$4;
}
})()], 0)),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"=","=",1152933628),new cljs.core.Keyword(null,"id","id",-1388402092),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"cast","cast",-1761029143),user_id,new cljs.core.Keyword(null,"uuid","uuid",-2145095719)], null)], null)], 0)),new cljs.core.Keyword(null,"*","*",-1294732318)], 0));
});
knoxx.backend.shape.db.users.credentials_for_users = (function knoxx$backend$shape$db$users$credentials_for_users(user_ids,org_id){
return honey.sql.helpers.order_by.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.where.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.from.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([honey.sql.helpers.select.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([new cljs.core.Keyword(null,"*","*",-1294732318)], 0)),new cljs.core.Keyword(null,"actor_credentials","actor_credentials",774592373)], 0)),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"and","and",-971899817),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"in","in",-1531184865),new cljs.core.Keyword(null,"user_id","user_id",993497112),cljs.core.mapv.cljs$core$IFn$_invoke$arity$2((function (id){
return new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"cast","cast",-1761029143),id,new cljs.core.Keyword(null,"uuid","uuid",-2145095719)], null);
}),user_ids)], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"=","=",1152933628),new cljs.core.Keyword(null,"org_id","org_id",1380185385),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"cast","cast",-1761029143),org_id,new cljs.core.Keyword(null,"uuid","uuid",-2145095719)], null)], null)], null)], 0)),new cljs.core.Keyword(null,"provider","provider",-302056900),new cljs.core.Keyword(null,"kind","kind",-717265803)], 0));
});

//# sourceMappingURL=knoxx.backend.shape.db.users.js.map
