

import "./cljs-runtime/shadow.module.server.prepend.js";
SHADOW_ENV.setLoaded("shadow.module.server.prepend.js");
import "./cljs-runtime/goog.debug.error.js";
SHADOW_ENV.setLoaded("goog.debug.error.js");
import "./cljs-runtime/goog.dom.nodetype.js";
SHADOW_ENV.setLoaded("goog.dom.nodetype.js");
import "./cljs-runtime/goog.asserts.asserts.js";
SHADOW_ENV.setLoaded("goog.asserts.asserts.js");
import "./cljs-runtime/goog.reflect.reflect.js";
SHADOW_ENV.setLoaded("goog.reflect.reflect.js");
import "./cljs-runtime/goog.math.long.js";
SHADOW_ENV.setLoaded("goog.math.long.js");
import "./cljs-runtime/goog.math.integer.js";
SHADOW_ENV.setLoaded("goog.math.integer.js");
import "./cljs-runtime/goog.dom.htmlelement.js";
SHADOW_ENV.setLoaded("goog.dom.htmlelement.js");
import "./cljs-runtime/goog.dom.tagname.js";
SHADOW_ENV.setLoaded("goog.dom.tagname.js");
import "./cljs-runtime/goog.dom.element.js";
SHADOW_ENV.setLoaded("goog.dom.element.js");
import "./cljs-runtime/goog.asserts.dom.js";
SHADOW_ENV.setLoaded("goog.asserts.dom.js");
import "./cljs-runtime/goog.dom.asserts.js";
SHADOW_ENV.setLoaded("goog.dom.asserts.js");
import "./cljs-runtime/goog.functions.functions.js";
SHADOW_ENV.setLoaded("goog.functions.functions.js");
import "./cljs-runtime/goog.string.typedstring.js";
SHADOW_ENV.setLoaded("goog.string.typedstring.js");
import "./cljs-runtime/goog.string.const.js";
SHADOW_ENV.setLoaded("goog.string.const.js");
import "./cljs-runtime/goog.html.trustedtypes.js";
SHADOW_ENV.setLoaded("goog.html.trustedtypes.js");
import "./cljs-runtime/goog.html.safescript.js";
SHADOW_ENV.setLoaded("goog.html.safescript.js");
import "./cljs-runtime/goog.fs.url.js";
SHADOW_ENV.setLoaded("goog.fs.url.js");
import "./cljs-runtime/goog.fs.blob.js";
SHADOW_ENV.setLoaded("goog.fs.blob.js");
import "./cljs-runtime/goog.html.trustedresourceurl.js";
SHADOW_ENV.setLoaded("goog.html.trustedresourceurl.js");
import "./cljs-runtime/goog.string.internal.js";
SHADOW_ENV.setLoaded("goog.string.internal.js");
import "./cljs-runtime/goog.html.safeurl.js";
SHADOW_ENV.setLoaded("goog.html.safeurl.js");
import "./cljs-runtime/goog.html.safestyle.js";
SHADOW_ENV.setLoaded("goog.html.safestyle.js");
import "./cljs-runtime/goog.object.object.js";
SHADOW_ENV.setLoaded("goog.object.object.js");
import "./cljs-runtime/goog.html.safestylesheet.js";
SHADOW_ENV.setLoaded("goog.html.safestylesheet.js");
import "./cljs-runtime/goog.flags.flags.js";
SHADOW_ENV.setLoaded("goog.flags.flags.js");
import "./cljs-runtime/goog.labs.useragent.useragent.js";
SHADOW_ENV.setLoaded("goog.labs.useragent.useragent.js");
import "./cljs-runtime/goog.labs.useragent.util.js";
SHADOW_ENV.setLoaded("goog.labs.useragent.util.js");
import "./cljs-runtime/goog.labs.useragent.highentropy.highentropyvalue.js";
SHADOW_ENV.setLoaded("goog.labs.useragent.highentropy.highentropyvalue.js");
import "./cljs-runtime/goog.labs.useragent.chromium_rebrands.js";
SHADOW_ENV.setLoaded("goog.labs.useragent.chromium_rebrands.js");
import "./cljs-runtime/goog.labs.useragent.highentropy.highentropydata.js";
SHADOW_ENV.setLoaded("goog.labs.useragent.highentropy.highentropydata.js");
import "./cljs-runtime/goog.labs.useragent.browser.js";
SHADOW_ENV.setLoaded("goog.labs.useragent.browser.js");
import "./cljs-runtime/goog.array.array.js";
SHADOW_ENV.setLoaded("goog.array.array.js");
import "./cljs-runtime/goog.dom.tags.js";
SHADOW_ENV.setLoaded("goog.dom.tags.js");
import "./cljs-runtime/goog.html.safehtml.js";
SHADOW_ENV.setLoaded("goog.html.safehtml.js");
import "./cljs-runtime/goog.html.uncheckedconversions.js";
SHADOW_ENV.setLoaded("goog.html.uncheckedconversions.js");
import "./cljs-runtime/goog.dom.safe.js";
SHADOW_ENV.setLoaded("goog.dom.safe.js");
import "./cljs-runtime/goog.string.string.js";
SHADOW_ENV.setLoaded("goog.string.string.js");
import "./cljs-runtime/goog.collections.maps.js";
SHADOW_ENV.setLoaded("goog.collections.maps.js");
import "./cljs-runtime/goog.structs.structs.js";
SHADOW_ENV.setLoaded("goog.structs.structs.js");
import "./cljs-runtime/goog.uri.utils.js";
SHADOW_ENV.setLoaded("goog.uri.utils.js");
import "./cljs-runtime/goog.uri.uri.js";
SHADOW_ENV.setLoaded("goog.uri.uri.js");
import "./cljs-runtime/goog.string.stringbuffer.js";
SHADOW_ENV.setLoaded("goog.string.stringbuffer.js");
import "./cljs-runtime/cljs.core.js";
SHADOW_ENV.setLoaded("cljs.core.js");
import "./cljs-runtime/shadow.js.js";
SHADOW_ENV.setLoaded("shadow.js.js");
import "./cljs-runtime/shadow.esm.esm_import$ws.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$ws.js");
import "./cljs-runtime/shadow.js.shim.module$ws$default.js";
SHADOW_ENV.setLoaded("shadow.js.shim.module$ws$default.js");
import "./cljs-runtime/clojure.string.js";
SHADOW_ENV.setLoaded("clojure.string.js");
import "./cljs-runtime/cljs.tools.reader.impl.utils.js";
SHADOW_ENV.setLoaded("cljs.tools.reader.impl.utils.js");
import "./cljs-runtime/cljs.tools.reader.reader_types.js";
SHADOW_ENV.setLoaded("cljs.tools.reader.reader_types.js");
import "./cljs-runtime/cljs.tools.reader.impl.inspect.js";
SHADOW_ENV.setLoaded("cljs.tools.reader.impl.inspect.js");
import "./cljs-runtime/cljs.tools.reader.impl.errors.js";
SHADOW_ENV.setLoaded("cljs.tools.reader.impl.errors.js");
import "./cljs-runtime/cljs.tools.reader.impl.commons.js";
SHADOW_ENV.setLoaded("cljs.tools.reader.impl.commons.js");
import "./cljs-runtime/cljs.tools.reader.js";
SHADOW_ENV.setLoaded("cljs.tools.reader.js");
import "./cljs-runtime/cljs.tools.reader.edn.js";
SHADOW_ENV.setLoaded("cljs.tools.reader.edn.js");
import "./cljs-runtime/cljs.reader.js";
SHADOW_ENV.setLoaded("cljs.reader.js");
import "./cljs-runtime/shadow.remote.runtime.api.js";
SHADOW_ENV.setLoaded("shadow.remote.runtime.api.js");
import "./cljs-runtime/shadow.remote.runtime.shared.js";
SHADOW_ENV.setLoaded("shadow.remote.runtime.shared.js");
import "./cljs-runtime/shadow.esm.js";
SHADOW_ENV.setLoaded("shadow.esm.js");
import "./cljs-runtime/clojure.set.js";
SHADOW_ENV.setLoaded("clojure.set.js");
import "./cljs-runtime/com.cognitect.transit.util.js";
SHADOW_ENV.setLoaded("com.cognitect.transit.util.js");
import "./cljs-runtime/com.cognitect.transit.delimiters.js";
SHADOW_ENV.setLoaded("com.cognitect.transit.delimiters.js");
import "./cljs-runtime/com.cognitect.transit.caching.js";
SHADOW_ENV.setLoaded("com.cognitect.transit.caching.js");
import "./cljs-runtime/com.cognitect.transit.eq.js";
SHADOW_ENV.setLoaded("com.cognitect.transit.eq.js");
import "./cljs-runtime/com.cognitect.transit.types.js";
SHADOW_ENV.setLoaded("com.cognitect.transit.types.js");
import "./cljs-runtime/com.cognitect.transit.impl.decoder.js";
SHADOW_ENV.setLoaded("com.cognitect.transit.impl.decoder.js");
import "./cljs-runtime/com.cognitect.transit.impl.reader.js";
SHADOW_ENV.setLoaded("com.cognitect.transit.impl.reader.js");
import "./cljs-runtime/com.cognitect.transit.handlers.js";
SHADOW_ENV.setLoaded("com.cognitect.transit.handlers.js");
import "./cljs-runtime/com.cognitect.transit.impl.writer.js";
SHADOW_ENV.setLoaded("com.cognitect.transit.impl.writer.js");
import "./cljs-runtime/com.cognitect.transit.js";
SHADOW_ENV.setLoaded("com.cognitect.transit.js");
import "./cljs-runtime/cognitect.transit.js";
SHADOW_ENV.setLoaded("cognitect.transit.js");
import "./cljs-runtime/shadow.cljs.devtools.client.env.js";
SHADOW_ENV.setLoaded("shadow.cljs.devtools.client.env.js");
import "./cljs-runtime/clojure.core.protocols.js";
SHADOW_ENV.setLoaded("clojure.core.protocols.js");
import "./cljs-runtime/shadow.remote.runtime.cljs.js_builtins.js";
SHADOW_ENV.setLoaded("shadow.remote.runtime.cljs.js_builtins.js");
import "./cljs-runtime/clojure.datafy.js";
SHADOW_ENV.setLoaded("clojure.datafy.js");
import "./cljs-runtime/cljs.pprint.js";
SHADOW_ENV.setLoaded("cljs.pprint.js");
import "./cljs-runtime/clojure.walk.js";
SHADOW_ENV.setLoaded("clojure.walk.js");
import "./cljs-runtime/cljs.spec.gen.alpha.js";
SHADOW_ENV.setLoaded("cljs.spec.gen.alpha.js");
import "./cljs-runtime/cljs.spec.alpha.js";
SHADOW_ENV.setLoaded("cljs.spec.alpha.js");
import "./cljs-runtime/shadow.remote.runtime.writer.js";
SHADOW_ENV.setLoaded("shadow.remote.runtime.writer.js");
import "./cljs-runtime/goog.string.stringformat.js";
SHADOW_ENV.setLoaded("goog.string.stringformat.js");
import "./cljs-runtime/cljs.repl.js";
SHADOW_ENV.setLoaded("cljs.repl.js");
import "./cljs-runtime/shadow.remote.runtime.obj_support.js";
SHADOW_ENV.setLoaded("shadow.remote.runtime.obj_support.js");
import "./cljs-runtime/shadow.remote.runtime.tap_support.js";
SHADOW_ENV.setLoaded("shadow.remote.runtime.tap_support.js");
import "./cljs-runtime/shadow.remote.runtime.eval_support.js";
SHADOW_ENV.setLoaded("shadow.remote.runtime.eval_support.js");
import "./cljs-runtime/shadow.cljs.devtools.client.shared.js";
SHADOW_ENV.setLoaded("shadow.cljs.devtools.client.shared.js");
import "./cljs-runtime/shadow.cljs.devtools.client.node_esm.js";
SHADOW_ENV.setLoaded("shadow.cljs.devtools.client.node_esm.js");
import "./cljs-runtime/knoxx.backend.domain.time.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.time.js");
import "./cljs-runtime/shadow.esm.esm_import$node_child_process.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$node_child_process.js");
import "./cljs-runtime/shadow.esm.esm_import$node_crypto.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$node_crypto.js");
import "./cljs-runtime/shadow.esm.esm_import$node_os.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$node_os.js");
import "./cljs-runtime/shadow.esm.esm_import$node_util.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$node_util.js");
import "./cljs-runtime/knoxx.backend.domain.realtime.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.realtime.js");
import "./cljs-runtime/malli.impl.util.js";
SHADOW_ENV.setLoaded("malli.impl.util.js");
import "./cljs-runtime/malli.impl.regex.js";
SHADOW_ENV.setLoaded("malli.impl.regex.js");
import "./cljs-runtime/malli.registry.js";
SHADOW_ENV.setLoaded("malli.registry.js");
import "./cljs-runtime/borkdude.dynaload.js";
SHADOW_ENV.setLoaded("borkdude.dynaload.js");
import "./cljs-runtime/malli.sci.js";
SHADOW_ENV.setLoaded("malli.sci.js");
import "./cljs-runtime/malli.core.js";
SHADOW_ENV.setLoaded("malli.core.js");
import "./cljs-runtime/malli.util.js";
SHADOW_ENV.setLoaded("malli.util.js");
import "./cljs-runtime/malli.error.js";
SHADOW_ENV.setLoaded("malli.error.js");
import "./cljs-runtime/knoxx.backend.shape.agent.message.js";
SHADOW_ENV.setLoaded("knoxx.backend.shape.agent.message.js");
import "./cljs-runtime/knoxx.backend.shape.agent.js";
SHADOW_ENV.setLoaded("knoxx.backend.shape.agent.js");
import "./cljs-runtime/knoxx.backend.domain.action.run_state.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.action.run_state.js");
import "./cljs-runtime/knoxx.backend.domain.extension_runtime.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.extension_runtime.js");
import "./cljs-runtime/knoxx.backend.domain.actor.scope.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.actor.scope.js");
import "./cljs-runtime/open_hax.contract_runtime.manifest.js";
SHADOW_ENV.setLoaded("open_hax.contract_runtime.manifest.js");
import "./cljs-runtime/knoxx.backend.domain.resources.namespace_file.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.resources.namespace_file.js");
import "./cljs-runtime/knoxx.backend.law.contracts.js";
SHADOW_ENV.setLoaded("knoxx.backend.law.contracts.js");
import "./cljs-runtime/shadow.esm.esm_import$node_fs.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$node_fs.js");
import "./cljs-runtime/shadow.esm.esm_import$node_fs$promises.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$node_fs$promises.js");
import "./cljs-runtime/shadow.esm.esm_import$node_path.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$node_path.js");
import "./cljs-runtime/knoxx.backend.domain.contracts.loader.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.contracts.loader.js");
import "./cljs-runtime/knoxx.backend.domain.models.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.models.js");
import "./cljs-runtime/shadow.esm.esm_import$$open_hax$eta_mu_cli.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$$open_hax$eta_mu_cli.js");
import "./cljs-runtime/knoxx.backend.extern.promise.js";
SHADOW_ENV.setLoaded("knoxx.backend.extern.promise.js");
import "./cljs-runtime/knoxx.backend.extern.eta_mu.js";
SHADOW_ENV.setLoaded("knoxx.backend.extern.eta_mu.js");
import "./cljs-runtime/knoxx.backend.extern.js.js";
SHADOW_ENV.setLoaded("knoxx.backend.extern.js.js");
import "./cljs-runtime/knoxx.backend.extern.extension.js";
SHADOW_ENV.setLoaded("knoxx.backend.extern.extension.js");
import "./cljs-runtime/open_hax.contract_runtime.agent.reasoning.js";
SHADOW_ENV.setLoaded("open_hax.contract_runtime.agent.reasoning.js");
import "./cljs-runtime/knoxx.backend.domain.agent.reasoning.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.agent.reasoning.js");
import "./cljs-runtime/knoxx.backend.extern.agent_message.js";
SHADOW_ENV.setLoaded("knoxx.backend.extern.agent_message.js");
import "./cljs-runtime/knoxx.backend.infra.agent.message.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.agent.message.js");
import "./cljs-runtime/knoxx.backend.infra.agent.content_codec.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.agent.content_codec.js");
import "./cljs-runtime/knoxx.backend.infra.stores.message_source.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.stores.message_source.js");
import "./cljs-runtime/knoxx.backend.infra.agent.history.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.agent.history.js");
import "./cljs-runtime/knoxx.backend.extern.json.js";
SHADOW_ENV.setLoaded("knoxx.backend.extern.json.js");
import "./cljs-runtime/promesa.protocols.js";
SHADOW_ENV.setLoaded("promesa.protocols.js");
import "./cljs-runtime/promesa.util.js";
SHADOW_ENV.setLoaded("promesa.util.js");
import "./cljs-runtime/promesa.impl.promise.js";
SHADOW_ENV.setLoaded("promesa.impl.promise.js");
import "./cljs-runtime/promesa.exec.js";
SHADOW_ENV.setLoaded("promesa.exec.js");
import "./cljs-runtime/promesa.impl.js";
SHADOW_ENV.setLoaded("promesa.impl.js");
import "./cljs-runtime/promesa.core.js";
SHADOW_ENV.setLoaded("promesa.core.js");
import "./cljs-runtime/knoxx.backend.extern.fetch.js";
SHADOW_ENV.setLoaded("knoxx.backend.extern.fetch.js");
import "./cljs-runtime/knoxx.backend.infra.clients.proxx.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.clients.proxx.js");
import "./cljs-runtime/knoxx.backend.infra.agent.provider.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.agent.provider.js");
import "./cljs-runtime/knoxx.backend.infra.agent.provider.eta_mu.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.agent.provider.eta_mu.js");
import "./cljs-runtime/knoxx.backend.infra.agent.session_registry.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.agent.session_registry.js");
import "./cljs-runtime/knoxx.backend.infra.clients.github.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.clients.github.js");
import "./cljs-runtime/knoxx.backend.infra.mongo_client.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.mongo_client.js");
import "./cljs-runtime/knoxx.backend.infra.auth.token_hash.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.auth.token_hash.js");
import "./cljs-runtime/knoxx.backend.extern.agent_turn_node.js";
SHADOW_ENV.setLoaded("knoxx.backend.extern.agent_turn_node.js");
import "./cljs-runtime/knoxx.backend.infra.system_instance.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.system_instance.js");
import "./cljs-runtime/knoxx.backend.infra.stores.mongo_policy_directory.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.stores.mongo_policy_directory.js");
import "./cljs-runtime/knoxx.backend.infra.stores.mongo_policy_roles.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.stores.mongo_policy_roles.js");
import "./cljs-runtime/knoxx.backend.infra.registry.tools.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.registry.tools.js");
import "./cljs-runtime/knoxx.backend.infra.stores.mongo_policy_tools.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.stores.mongo_policy_tools.js");
import "./cljs-runtime/knoxx.backend.infra.stores.mongo_policy_actor_credentials.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.stores.mongo_policy_actor_credentials.js");
import "./cljs-runtime/knoxx.backend.infra.stores.mongo_policy_audit_events.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.stores.mongo_policy_audit_events.js");
import "./cljs-runtime/knoxx.backend.infra.stores.mongo_policy_data_lakes.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.stores.mongo_policy_data_lakes.js");
import "./cljs-runtime/knoxx.backend.infra.stores.mongo_policy_invites.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.stores.mongo_policy_invites.js");
import "./cljs-runtime/knoxx.backend.infra.stores.mongo_policy_studio.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.stores.mongo_policy_studio.js");
import "./cljs-runtime/knoxx.backend.infra.stores.mongo_policy_store.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.stores.mongo_policy_store.js");
import "./cljs-runtime/knoxx.backend.infra.config.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.config.js");
import "./cljs-runtime/knoxx.backend.infra.defaults.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.defaults.js");
import "./cljs-runtime/knoxx.backend.domain.agent.agent_templates.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.agent.agent_templates.js");
import "./cljs-runtime/knoxx.backend.domain.contracts.roles.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.contracts.roles.js");
import "./cljs-runtime/cljs.math.js";
SHADOW_ENV.setLoaded("cljs.math.js");
import "./cljs-runtime/goog.i18n.datetimesymbols.js";
SHADOW_ENV.setLoaded("goog.i18n.datetimesymbols.js");
import "./cljs-runtime/goog.date.date.js";
SHADOW_ENV.setLoaded("goog.date.date.js");
import "./cljs-runtime/goog.date.utcdatetime.js";
SHADOW_ENV.setLoaded("goog.date.utcdatetime.js");
import "./cljs-runtime/malli.transform.js";
SHADOW_ENV.setLoaded("malli.transform.js");
import "./cljs-runtime/open_hax.contracts.schema.js";
SHADOW_ENV.setLoaded("open_hax.contracts.schema.js");
import "./cljs-runtime/knoxx.backend.domain.policy.protocol.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.policy.protocol.js");
import "./cljs-runtime/knoxx.backend.domain.policy.edn_adapter.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.policy.edn_adapter.js");
import "./cljs-runtime/knoxx.backend.infra.db.actors.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.db.actors.js");
import "./cljs-runtime/knoxx.backend.infra.db.policy.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.db.policy.js");
import "./cljs-runtime/shadow.esm.esm_import$nodemailer.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$nodemailer.js");
import "./cljs-runtime/knoxx.backend.infra.auth.session.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.auth.session.js");
import "./cljs-runtime/knoxx.backend.domain.error_observatory.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.error_observatory.js");
import "./cljs-runtime/knoxx.backend.extern.fastify.js";
SHADOW_ENV.setLoaded("knoxx.backend.extern.fastify.js");
import "./cljs-runtime/knoxx.backend.infra.http.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.http.js");
import "./cljs-runtime/knoxx.backend.runtime.state.js";
SHADOW_ENV.setLoaded("knoxx.backend.runtime.state.js");
import "./cljs-runtime/knoxx.backend.infra.auth.authz.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.auth.authz.js");
import "./cljs-runtime/knoxx.backend.infra.stores.session_store_registry.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.stores.session_store_registry.js");
import "./cljs-runtime/knoxx.backend.infra.clients.openplanner.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.clients.openplanner.js");
import "./cljs-runtime/knoxx.backend.shape.session_persistence.js";
SHADOW_ENV.setLoaded("knoxx.backend.shape.session_persistence.js");
import "./cljs-runtime/knoxx.backend.domain.label.quality.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.label.quality.js");
import "./cljs-runtime/knoxx.backend.domain.graph.expansion_policy.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.graph.expansion_policy.js");
import "./cljs-runtime/knoxx.backend.domain.graph.policy_registry.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.graph.policy_registry.js");
import "./cljs-runtime/knoxx.backend.infra.openplanner.memory.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.openplanner.memory.js");
import "./cljs-runtime/knoxx.backend.infra.document_state.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.document_state.js");
import "./cljs-runtime/knoxx.backend.extern.row_extra.js";
SHADOW_ENV.setLoaded("knoxx.backend.extern.row_extra.js");
import "./cljs-runtime/knoxx.backend.domain.contracts.sources.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.contracts.sources.js");
import "./cljs-runtime/knoxx.backend.domain.contracts.resolve.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.contracts.resolve.js");
import "./cljs-runtime/knoxx.backend.domain.mcp.mcp_bridge.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.mcp.mcp_bridge.js");
import "./cljs-runtime/knoxx.backend.infra.tooling.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.tooling.js");
import "./cljs-runtime/knoxx.backend.infra.core_memory.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.core_memory.js");
import "./cljs-runtime/knoxx.backend.domain.text.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.text.js");
import "./cljs-runtime/malli.json_schema.js";
SHADOW_ENV.setLoaded("malli.json_schema.js");
import "./cljs-runtime/knoxx.backend.extern.tools.js";
SHADOW_ENV.setLoaded("knoxx.backend.extern.tools.js");
import "./cljs-runtime/knoxx.backend.domain.tools.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.tools.js");
import "./cljs-runtime/knoxx.backend.infra.openplanner.semantic.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.openplanner.semantic.js");
import "./cljs-runtime/knoxx.backend.domain.discord.rest_client.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.discord.rest_client.js");
import "./cljs-runtime/knoxx.backend.extern.discord.js";
SHADOW_ENV.setLoaded("knoxx.backend.extern.discord.js");
import "./cljs-runtime/shadow.esm.esm_import$puppeteer_core.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$puppeteer_core.js");
import "./cljs-runtime/knoxx.backend.infra.svg_render.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.svg_render.js");
import "./cljs-runtime/open_hax.contract_runtime.agent.context.js";
SHADOW_ENV.setLoaded("open_hax.contract_runtime.agent.context.js");
import "./cljs-runtime/knoxx.backend.domain.agent.agent_context.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.agent.agent_context.js");
import "./cljs-runtime/knoxx.backend.domain.actor.credentials.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.actor.credentials.js");
import "./cljs-runtime/knoxx.backend.domain.media.remote_client.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.media.remote_client.js");
import "./cljs-runtime/knoxx.backend.domain.media.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.media.js");
import "./cljs-runtime/knoxx.backend.domain.discord.tools.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.discord.tools.js");
import "./cljs-runtime/shadow.esm.esm_import$discord.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$discord.js");
import "./cljs-runtime/shadow.esm.esm_import$$discordjs$voice.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$$discordjs$voice.js");
import "./cljs-runtime/shadow.esm.esm_import$prism_media.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$prism_media.js");
import "./cljs-runtime/shadow.esm.esm_import$node_module.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$node_module.js");
import "./cljs-runtime/shadow.esm.esm_import$node_stream.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$node_stream.js");
import "./cljs-runtime/knoxx.backend.domain.discord.gateway.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.discord.gateway.js");
import "./cljs-runtime/knoxx.backend.domain.voice.client.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.voice.client.js");
import "./cljs-runtime/knoxx.backend.infra.clients.knoxx_control.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.clients.knoxx_control.js");
import "./cljs-runtime/knoxx.backend.infra.stores.mongo_session_store.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.stores.mongo_session_store.js");
import "./cljs-runtime/knoxx.backend.domain.discord.voice_tools.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.discord.voice_tools.js");
import "./cljs-runtime/knoxx.backend.domain.event.tools.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.event.tools.js");
import "./cljs-runtime/knoxx.backend.domain.actor.mailbox.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.actor.mailbox.js");
import "./cljs-runtime/knoxx.backend.domain.actor.tools.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.actor.tools.js");
import "./cljs-runtime/knoxx.backend.infra.openplanner.tools.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.openplanner.tools.js");
import "./cljs-runtime/knoxx.backend.domain.music.audd_client.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.music.audd_client.js");
import "./cljs-runtime/knoxx.backend.domain.music.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.music.js");
import "./cljs-runtime/knoxx.backend.domain.openutau.openutau.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.openutau.openutau.js");
import "./cljs-runtime/knoxx.backend.domain.openutau.tools.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.openutau.tools.js");
import "./cljs-runtime/knoxx.backend.domain.voice.tools.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.voice.tools.js");
import "./cljs-runtime/knoxx.backend.domain.media.blaze_client.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.media.blaze_client.js");
import "./cljs-runtime/knoxx.backend.domain.media.blaze.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.media.blaze.js");
import "./cljs-runtime/knoxx.backend.domain.bluesky.client.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.bluesky.client.js");
import "./cljs-runtime/knoxx.backend.domain.bluesky.bluesky.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.bluesky.bluesky.js");
import "./cljs-runtime/knoxx.backend.domain.media.multimodal.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.media.multimodal.js");
import "./cljs-runtime/knoxx.backend.domain.media.workspace.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.media.workspace.js");
import "./cljs-runtime/knoxx.backend.domain.sandbox_container.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.sandbox_container.js");
import "./cljs-runtime/knoxx.backend.tools.mcp.js";
SHADOW_ENV.setLoaded("knoxx.backend.tools.mcp.js");
import "./cljs-runtime/knoxx.backend.domain.contracts.client.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.contracts.client.js");
import "./cljs-runtime/knoxx.backend.domain.contracts.tools.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.contracts.tools.js");
import "./cljs-runtime/shadow.esm.esm_import$node_net.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$node_net.js");
import "./cljs-runtime/knoxx.backend.domain.nrepl.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.nrepl.js");
import "./cljs-runtime/knoxx.backend.domain.session_mycology.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.session_mycology.js");
import "./cljs-runtime/knoxx.backend.infra.agent.hydration.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.agent.hydration.js");
import "./cljs-runtime/knoxx.backend.infra.agent.tool_catalog.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.agent.tool_catalog.js");
import "./cljs-runtime/knoxx.backend.infra.stores.composite_message_source.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.stores.composite_message_source.js");
import "./cljs-runtime/knoxx.backend.infra.stores.openplanner_message_source.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.stores.openplanner_message_source.js");
import "./cljs-runtime/knoxx.backend.infra.stores.mongo_message_source.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.stores.mongo_message_source.js");
import "./cljs-runtime/knoxx.backend.infra.agent.session.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.agent.session.js");
import "./cljs-runtime/knoxx.backend.infra.agent.runtime.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.agent.runtime.js");
import "./cljs-runtime/knoxx.backend.infra.stores.mongo_temp_memory.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.stores.mongo_temp_memory.js");
import "./cljs-runtime/knoxx.backend.infra.temp_memory.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.temp_memory.js");
import "./cljs-runtime/knoxx.backend.shape.pipeline.js";
SHADOW_ENV.setLoaded("knoxx.backend.shape.pipeline.js");
import "./cljs-runtime/knoxx.backend.domain.action.registry.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.action.registry.js");
import "./cljs-runtime/open_hax.contract_runtime.filter.registry.js";
SHADOW_ENV.setLoaded("open_hax.contract_runtime.filter.registry.js");
import "./cljs-runtime/knoxx.backend.domain.filter.registry.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.filter.registry.js");
import "./cljs-runtime/knoxx.backend.domain.resources.loader.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.resources.loader.js");
import "./cljs-runtime/open_hax.contract_runtime.store.protocol.js";
SHADOW_ENV.setLoaded("open_hax.contract_runtime.store.protocol.js");
import "./cljs-runtime/open_hax.contract_runtime.store.law.js";
SHADOW_ENV.setLoaded("open_hax.contract_runtime.store.law.js");
import "./cljs-runtime/open_hax.contract_runtime.store.memory.js";
SHADOW_ENV.setLoaded("open_hax.contract_runtime.store.memory.js");
import "./cljs-runtime/open_hax.contract_runtime.store.registry.js";
SHADOW_ENV.setLoaded("open_hax.contract_runtime.store.registry.js");
import "./cljs-runtime/knoxx.backend.infra.store.registry.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.store.registry.js");
import "./cljs-runtime/knoxx.backend.contract_runtime_deps.js";
SHADOW_ENV.setLoaded("knoxx.backend.contract_runtime_deps.js");
import "./cljs-runtime/knoxx.backend.extern.agent_turn_media.js";
SHADOW_ENV.setLoaded("knoxx.backend.extern.agent_turn_media.js");
import "./cljs-runtime/knoxx.backend.extern.agent_turn_prompt.js";
SHADOW_ENV.setLoaded("knoxx.backend.extern.agent_turn_prompt.js");
import "./cljs-runtime/knoxx.backend.extern.agent_turn_result.js";
SHADOW_ENV.setLoaded("knoxx.backend.extern.agent_turn_result.js");
import "./cljs-runtime/open_hax.contract_runtime.agent.text_delta.js";
SHADOW_ENV.setLoaded("open_hax.contract_runtime.agent.text_delta.js");
import "./cljs-runtime/knoxx.backend.domain.agent.text_delta.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.agent.text_delta.js");
import "./cljs-runtime/knoxx.backend.domain.agent.content.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.agent.content.js");
import "./cljs-runtime/knoxx.backend.infra.stores.mongo_rate_limits.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.stores.mongo_rate_limits.js");
import "./cljs-runtime/knoxx.backend.infra.agent.policy.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.agent.policy.js");
import "./cljs-runtime/open_hax.contract_runtime.agent.tool_lifecycle.js";
SHADOW_ENV.setLoaded("open_hax.contract_runtime.agent.tool_lifecycle.js");
import "./cljs-runtime/knoxx.backend.domain.agent.tool_lifecycle.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.agent.tool_lifecycle.js");
import "./cljs-runtime/open_hax.contract_runtime.agent.turn_guards.js";
SHADOW_ENV.setLoaded("open_hax.contract_runtime.agent.turn_guards.js");
import "./cljs-runtime/knoxx.backend.domain.agent.turn_guards.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.agent.turn_guards.js");
import "./cljs-runtime/knoxx.backend.infra.agent.tools.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.agent.tools.js");
import "./cljs-runtime/knoxx.backend.infra.agent.stream.provider_events.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.agent.stream.provider_events.js");
import "./cljs-runtime/knoxx.backend.infra.agent.stream.sinks.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.agent.stream.sinks.js");
import "./cljs-runtime/knoxx.backend.domain.voice.turn_control.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.voice.turn_control.js");
import "./cljs-runtime/knoxx.backend.infra.agent.stream.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.agent.stream.js");
import "./cljs-runtime/knoxx.backend.infra.agent.transcript.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.agent.transcript.js");
import "./cljs-runtime/knoxx.backend.extern.proxx.js";
SHADOW_ENV.setLoaded("knoxx.backend.extern.proxx.js");
import "./cljs-runtime/knoxx.backend.infra.stores.mongo_session_titles.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.stores.mongo_session_titles.js");
import "./cljs-runtime/knoxx.backend.infra.stores.session_titles.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.stores.session_titles.js");
import "./cljs-runtime/knoxx.backend.infra.agent.turn.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.agent.turn.js");
import "./cljs-runtime/knoxx.backend.infra.agent.recovery.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.agent.recovery.js");
import "./cljs-runtime/knoxx.backend.infra.agent.resume.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.agent.resume.js");
import "./cljs-runtime/knoxx.backend.infra.routes.users.admin.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.routes.users.admin.js");
import "./cljs-runtime/knoxx.backend.infra.routes.admin.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.routes.admin.js");
import "./cljs-runtime/open_hax.contract_runtime.action.anonymous.js";
SHADOW_ENV.setLoaded("open_hax.contract_runtime.action.anonymous.js");
import "./cljs-runtime/open_hax.contract_runtime.action.interpreter.js";
SHADOW_ENV.setLoaded("open_hax.contract_runtime.action.interpreter.js");
import "./cljs-runtime/knoxx.backend.domain.action.interpreter.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.action.interpreter.js");
import "./cljs-runtime/knoxx.backend.extern.agent_runner.js";
SHADOW_ENV.setLoaded("knoxx.backend.extern.agent_runner.js");
import "./cljs-runtime/knoxx.backend.infra.agent.runner.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.agent.runner.js");
import "./cljs-runtime/knoxx.backend.domain.action.start_agent_session.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.action.start_agent_session.js");
import "./cljs-runtime/knoxx.backend.domain.action.run_pipeline.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.action.run_pipeline.js");
import "./cljs-runtime/open_hax.contract_runtime.condition.registry.js";
SHADOW_ENV.setLoaded("open_hax.contract_runtime.condition.registry.js");
import "./cljs-runtime/knoxx.backend.domain.condition.registry.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.condition.registry.js");
import "./cljs-runtime/knoxx.backend.domain.event.normalize.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.event.normalize.js");
import "./cljs-runtime/knoxx.backend.domain.trigger.normalize.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.trigger.normalize.js");
import "./cljs-runtime/knoxx.backend.domain.event.dispatch.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.event.dispatch.js");
import "./cljs-runtime/knoxx.backend.macros.js";
SHADOW_ENV.setLoaded("knoxx.backend.macros.js");
import "./cljs-runtime/knoxx.backend.infra.routes.actors.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.routes.actors.js");
import "./cljs-runtime/knoxx.backend.infra.agent.service.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.agent.service.js");
import "./cljs-runtime/knoxx.backend.shape.app_shapes.js";
SHADOW_ENV.setLoaded("knoxx.backend.shape.app_shapes.js");
import "./cljs-runtime/knoxx.backend.domain.schedule.runtime.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.schedule.runtime.js");
import "./cljs-runtime/open_hax.contract_runtime.driver.registry.js";
SHADOW_ENV.setLoaded("open_hax.contract_runtime.driver.registry.js");
import "./cljs-runtime/knoxx.backend.domain.driver.registry.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.driver.registry.js");
import "./cljs-runtime/knoxx.backend.domain.driver.builtin.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.driver.builtin.js");
import "./cljs-runtime/knoxx.backend.domain.source.runtime.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.source.runtime.js");
import "./cljs-runtime/knoxx.backend.domain.trigger.runtime.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.trigger.runtime.js");
import "./cljs-runtime/knoxx.backend.infra.event_runtime.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.event_runtime.js");
import "./cljs-runtime/knoxx.backend.infra.routes.resources.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.routes.resources.js");
import "./cljs-runtime/knoxx.backend.infra.routes.documents.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.routes.documents.js");
import "./cljs-runtime/knoxx.backend.law.guards.js";
SHADOW_ENV.setLoaded("knoxx.backend.law.guards.js");
import "./cljs-runtime/knoxx.backend.infra.stores.mongo_memory_sessions.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.stores.mongo_memory_sessions.js");
import "./cljs-runtime/knoxx.backend.shape.parse.js";
SHADOW_ENV.setLoaded("knoxx.backend.shape.parse.js");
import "./cljs-runtime/knoxx.backend.shape.memory_sessions.js";
SHADOW_ENV.setLoaded("knoxx.backend.shape.memory_sessions.js");
import "./cljs-runtime/knoxx.backend.infra.routes.memory.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.routes.memory.js");
import "./cljs-runtime/knoxx.backend.infra.routes.models.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.routes.models.js");
import "./cljs-runtime/knoxx.backend.domain.control.catalog.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.control.catalog.js");
import "./cljs-runtime/knoxx.backend.runtime.roles.js";
SHADOW_ENV.setLoaded("knoxx.backend.runtime.roles.js");
import "./cljs-runtime/knoxx.backend.infra.control_config.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.control_config.js");
import "./cljs-runtime/knoxx.backend.infra.routes.tools.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.routes.tools.js");
import "./cljs-runtime/knoxx.backend.extern.multipart.js";
SHADOW_ENV.setLoaded("knoxx.backend.extern.multipart.js");
import "./cljs-runtime/knoxx.backend.extern.websocket.js";
SHADOW_ENV.setLoaded("knoxx.backend.extern.websocket.js");
import "./cljs-runtime/knoxx.backend.infra.routes.voice.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.routes.voice.js");
import "./cljs-runtime/knoxx.backend.infra.routes.workspace_media.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.routes.workspace_media.js");
import "./cljs-runtime/knoxx.backend.domain.label.audio.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.label.audio.js");
import "./cljs-runtime/knoxx.backend.infra.routes.studio.discord_scan.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.routes.studio.discord_scan.js");
import "./cljs-runtime/knoxx.backend.infra.routes.studio.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.routes.studio.js");
import "./cljs-runtime/knoxx.backend.infra.routes.translation.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.routes.translation.js");
import "./cljs-runtime/knoxx.backend.infra.routes.app.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.routes.app.js");
import "./cljs-runtime/knoxx.backend.domain.discord.source.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.discord.source.js");
import "./cljs-runtime/knoxx.backend.domain.condition.builtin.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.condition.builtin.js");
import "./cljs-runtime/shadow.esm.esm_import$fastify.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$fastify.js");
import "./cljs-runtime/shadow.esm.esm_import$$fastify$cors.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$$fastify$cors.js");
import "./cljs-runtime/shadow.esm.esm_import$$fastify$websocket.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$$fastify$websocket.js");
import "./cljs-runtime/shadow.esm.esm_import$$fastify$multipart.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$$fastify$multipart.js");
import "./cljs-runtime/shadow.esm.esm_import$$fastify$cookie.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$$fastify$cookie.js");
import "./cljs-runtime/shadow.esm.esm_import$$fastify$formbody.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$$fastify$formbody.js");
import "./cljs-runtime/knoxx.backend.infra.http_server.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.http_server.js");
import "./cljs-runtime/knoxx.backend.infra.lifecycle.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.lifecycle.js");
import "./cljs-runtime/knoxx.backend.infra.core.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.core.js");
import "./cljs-runtime/knoxx.backend.domain.discord.discord_reaction_labels.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.discord.discord_reaction_labels.js");
import "./cljs-runtime/knoxx.backend.infra.graceful_shutdown.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.graceful_shutdown.js");
import "./cljs-runtime/knoxx.backend.infra.stores.mongo_run_store.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.stores.mongo_run_store.js");
import "./cljs-runtime/knoxx.backend.infra.stores.mongo_mcp_oauth.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.stores.mongo_mcp_oauth.js");
import "./cljs-runtime/knoxx.backend.infra.stores.session_flush.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.stores.session_flush.js");
import "./cljs-runtime/knoxx.backend.infra.routes.auth.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.routes.auth.js");
import "./cljs-runtime/knoxx.backend.domain.mcp.mcp_expose.js";
SHADOW_ENV.setLoaded("knoxx.backend.domain.mcp.mcp_expose.js");
import "./cljs-runtime/shadow.esm.esm_import$$modelcontextprotocol$sdk$server$mcp.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$$modelcontextprotocol$sdk$server$mcp.js");
import "./cljs-runtime/shadow.esm.esm_import$$modelcontextprotocol$sdk$server$streamableHttp.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$$modelcontextprotocol$sdk$server$streamableHttp.js");
import "./cljs-runtime/shadow.esm.esm_import$zod.js";
SHADOW_ENV.setLoaded("shadow.esm.esm_import$zod.js");
import "./cljs-runtime/knoxx.backend.infra.routes.mcp.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.routes.mcp.js");
import "./cljs-runtime/knoxx.backend.infra.eta_mu_session_ingester.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.eta_mu_session_ingester.js");
import "./cljs-runtime/knoxx.backend.infra.clients.opencode.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.clients.opencode.js");
import "./cljs-runtime/knoxx.backend.infra.source.opencode_session_ingester.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.source.opencode_session_ingester.js");
import "./cljs-runtime/knoxx.backend.infra.routes.tools.proxy.js";
SHADOW_ENV.setLoaded("knoxx.backend.infra.routes.tools.proxy.js");
import "./cljs-runtime/knoxx.backend.bootstrap.js";
SHADOW_ENV.setLoaded("knoxx.backend.bootstrap.js");
import "./cljs-runtime/knoxx.backend.entrypoint.js";
SHADOW_ENV.setLoaded("knoxx.backend.entrypoint.js");
import "./cljs-runtime/shadow.module.server.append.js";
SHADOW_ENV.setLoaded("shadow.module.server.append.js");


try { knoxx.backend.entrypoint.init(); } catch (e) { console.error("An error occurred when calling (knoxx.backend.entrypoint/init)"); console.error(e); }
shadow.cljs.devtools.client.env.module_loaded("server");