;; Π_STATE.sexp — Fork tax snapshot
;; Generated: 2026-06-15T05:06:47Z
;; Branch: feat/kanban-comments-parity
;; Base commit: 44844e3fc0bf5082beb19086c3b006d50ecc0ddf

(π-snapshot
  (branch "feat/kanban-comments-parity")
  (base-sha "44844e3fc0bf5082beb19086c3b006d50ecc0ddf")
  (timestamp "2026-06-15T05:06:47Z")

  (summary
    "Rheos ↔ Sol board-chat parity: realtime token streaming, lifecycle events, SSE reply fixes, dev server retry")

  (scope
    ;; Rheos
    (modified-rheos-config "packages/Rheos/ecosystem.config.cjs")
    (modified-rheos-chat-proxy "packages/Rheos/src/rheos/backend/infra/chat_proxy.cljs")
    (modified-rheos-http-server "packages/Rheos/src/rheos/backend/infra/http_server.cljs")

    ;; Sol
    (modified-sol-turn "packages/sol/src/cljs/open_hax/sol/infra/agent/turn.cljs")
    (added-sol-turn-test "packages/sol/test/cljs/open_hax/sol/infra/agent/turn_stream_test.cljs")

    ;; Notes
    (modified-notes "docs/notes/2026.06.14.22.24.55.md"))

  (excluded
    ;; Build artifacts — regenerated by shadow-cljs; gitignored but still tracked historically
    (dist-dev-sol "packages/sol/dist-dev/**" (reason "build artifacts"))
    (dist-dev-rheos "packages/Rheos/dist-dev/**" (reason "build artifacts"))
    ;; Lockfile — stale, regenerate on next pnpm install
    (lockfile "pnpm-lock.yaml" (reason "stale lock state"))
    ;; Session scratch / lock files
    (emacs-lock ".#migrating-sol.md" (reason "Emacs lock file"))
    (migration-scratch "migrating-sol.md" (reason "session scratch note, not curated for commit")))

  (concurrent-dirt
    (note "Workspace is single-agent for this branch; excluded paths above are generated/runtime/scratch, not another agent's work"))

  (verification
    (rheos-tests "passed — 34 tests, 85 assertions")
    (rheos-build "passed — shadow-cljs compile server")
    (sol-build "passed — shadow-cljs compile server")
    (sol-tests "blocked — missing namespace open-hax.contracts.policy.eval required by open_hax/contracts/policy/eval_test.cljs")
    (sol-lint "blocked — pre-existing EOF error in test/cljs/open_hax/sol/shape/parse_test.cljs")
    (ts-line-count "unchanged — 174537 lines")))

;; END Π_STATE
