;; Π_STATE.sexp — Fork tax snapshot
;; Generated: 2026-06-14T20:47 UTC
;; Branch: feat/kanban-comments-parity
;; Base commit: 4020a06a74d8c57d9004e88591f7358ae8caef42

(π-snapshot
  (branch "feat/kanban-comments-parity")
  (base-sha "4020a06a74d8c57d9004e88591f7358ae8caef42")
  (timestamp "2026-06-14T20:47:00Z")

  (summary
    "knoxx → sol namespace migration + new packages (Rheos UI, kanban-orchestrator, katamorph, mcp-contracts)")

  (scope
    ;; Deleted knoxx source + tests (~72k lines removed)
    (deleted-knoxx-src "packages/sol/src/cljs/knoxx/backend/**")
    (deleted-knoxx-tests "packages/sol/test/cljs/knoxx/backend/**")

    ;; New sol source under open_hax.sol namespace
    (added-sol-src "packages/sol/src/cljs/open_hax/sol/**")
    (added-sol-tests "packages/sol/test/cljs/open_hax/**")

    ;; New packages
    (added-rheos-src "packages/Rheos/src/rheos/**")
    (added-rheos-dist "packages/Rheos/dist-dev/")
    (added-kanban-orchestrator "packages/kanban-orchestrator/")
    (added-katamorph-test "packages/katamorph/test/")
    (added-mcp-contracts "packages/mcp-contracts/")
    (added-sol-staging "packages/sol-staging/")

    ;; Modified
    (modified-sol-entry "packages/sol/server.js")
    (modified-sol-shadow "packages/sol/shadow-cljs.edn")
    (modified-sol-pkg "packages/sol/package.json")
    (added-sol-gitignore "packages/sol/.gitignore")

    ;; Scripts
    (added-ts-guard "scripts/pre-commit-ts-guard.sh")
    (added-ts-count "scripts/ts-line-count.mjs")

    ;; Notes
    (added-notes "docs/notes/2026.06.14.*.md"))

  (excluded
    ;; dist-dev build artifacts — regenerated by shadow-cljs compile
    (dist-dev "packages/sol/dist-dev/**" (reason "build artifacts, gitignored in packages/sol/.gitignore"))
    ;; pnpm-lock — should be regenerated from pnpm install
    (lockfile "pnpm-lock.yaml" (reason "stale lock state, regenerate on next install")))

  (concurrent-dirt
    ;; None detected — workspace appears to have single-agent ownership of this migration
    (note "No concurrent agent dirt detected in this snapshot"))

  (verification
    (tests "skipped — knoxx tests deleted, sol tests not yet wired to CI")
    (build "skipped — shadow-cljs dev build state is in dist-dev (excluded)")
    (lint "not run")))

;; END Π_STATE
